export { default as AuthRoutes } from "./auth-routes"
export { default as DashboardRoutes } from "./dashboard-routes"
export { default as JobRoutes } from "./job-routes"
export { default as SettingsRoutes } from "./settings-routes"
export { default as TalentRoutes } from "./talent-routes"